swagger: "2.0"
info:
  description: >-
    The Customer KYC(Know Your Client) Verification API will validate the 3PP Customer KYC information with MTN Customer KYC information. 
    
  version: "0.1"
  title: MTN Customer KYC Verification API
host: api.chenosis.io
basePath : "/kycVerify/gh/v1"
securityDefinitions:
  OAuth2:
    type: oauth2
    flow: application
    tokenUrl: 'https://api.chenosis.io/oauth/client/accesstoken'
security:
  - OAuth2: []
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /customers/{customerId}:
    post:
      tags:
        - Customer KYC
      summary: Verify mtn customer kyc information against 3PP customer kyc information
      description: >-
        This endpoint is to enable trusted partners verify customer's KYC information passed in the request body. The verification logic will be carried 
        out at the process layer where each KYC attributes will be validated and given a percentage score (between 0 - 100) based on their matching record 
        on the network downstream system
      parameters:
        - name: customerId
          in: path
          description: Phone number of the customer, the format must be E.123
          required: true
          type: string
        - in: body
          name: body
          description: Request body
          required: true
          schema:
            $ref: '#/definitions/KYCRequestObject'
      responses:
        "200":
          description: Callback Success Response
          schema:
            $ref: '#/definitions/KYCResponseObject'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/Error400'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error401'
        '403':
          description: Forbidden
          schema:
            $ref: '#/definitions/Error403'
        '404':
          description: Not Found
          schema:
            $ref: '#/definitions/Error404'
        '405':
          description: Method No Allowed
          schema:
            $ref: "#/definitions/Error405"
        '415':
          description: Unsupported Media Type
          schema:
            $ref: "#/definitions/Error415"
        '408':
          description: Time out
          schema:
            $ref: "#/definitions/Error408"
        '500':
          description: Internal Server Error
          schema:
            $ref: "#/definitions/Error500"
definitions:
  KYCRequestObject:
    type: object
    required:
      - firstName
      - lastName
      - phoneNumber
      - emailAddress
      - nationalIdNumber
      - streetAddress
      - city
      - postCode
      - country
    properties:
      firstName:
        type: string
        example: John
        description: Customer's first name
      lastName:
        type: string
        example: Doe
        description: Customer's last name
      phoneNumber:
        type: string
        example: 233594082483
        description: Customer's phone number
      emailAddress:
        type: string
        example: john.doe@email.com
        description: Customer first name 
      nationalIdNumber:
        type: number
        example: 123456789
        description: Customer's National ID Number
      streetAddress:
        type: string
        example: 1st Park Avenue, Mzansi, Johannesburg
        description: Customer's street address
      city:
        type: string
        example: Johannesburg
        description: Customer's city
      postCode:
        type: string
        example: 20200
        description: Customer's postal code
      country:
        type: string
        example: South Africa
        description: Customer's country
  KYCResponseObject:
    required:
      - customerId
      - data
      - statusCode
      - statusMessage
    type: object
    properties:
      statusCode:
        type: string
        description: HTTP error code extension
        example: '0000'
      statusMessage:
        type: string
        description: Message.
        example: Success.
      customerId:
        type: string
        description: MSISDN of the customer provided in the input as customerId
        example: '256789999781'
      transactionId:
        type: string
        description: transaction ID From the backend provider system for tracing.
        example: 232TXYZ-212
      data:
        $ref: '#/definitions/dataObject'
  dataObject:
    type: object
    properties:
      firstName:
        type: number
        example: 100
        description: Score in percentage based on match between request and backend record
      lastName:
        type: number
        example: 100
        description: Score in percentage based on match between request and backend record
      phoneNumber:
        type: number
        example: 100
        description: Score in percentage based on match between request and backend record
      emailAddress:
        type: number
        example: 100
        description: Score in percentage based on match between request and backend record 
      nationalIdNumber:
        type: number
        example: 100
        description: Score in percentage based on match between request and backend record
      streetAddress:
        type: number
        example: 100
        description: Score in percentage based on match between request and backend record
      city:
        type: number
        example: 100
        description: Score in percentage based on match between request and backend record
      postCode:
        type: number
        example: 100
        description: Score in percentage based on match between request and backend record
      country:
        type: number
        example: 100
        description: Score in percentage based on match between request and backend record 
  Error400:
      type: object
      properties:
        statusCode:
          type: string
          description: HTTP error code extension
          example: "5000"
        statusMessage:
          type: string
          description: "5000-The input parameters provided are invalid"
          example: "Bad Request"
        supportMessage:
          type: string
          description: "1. Unsupported input, please enter a valid 'msisdn' value. \n 2. attribute name missing Both Msisdn in path param and request body should be same.\n3. attribute name cannot be null.\n4. attribute name missing"
          example: "Unsupported input, please enter a valid 'msisdn' value"
        transactionId:
          type: string
          description: "Id for tracing."
          example: "fg545f-cf4gg4fd55-fdg85hg6"
  Error401:
      type: object
      properties:
        statusCode:
          type: string
          description: HTTP error code extension
          example: "4000"
        statusMessage:
          type: string
          description: "Short description of the error"
          example: "Unauthorised"
        supportMessage:
          type: string
          description: "Longer description of the error"
          example: "Please verify token environment or access token or API key"
        transactionId:
          type: string
          description: "Id for tracing."
          example: "fg545f-cf4gg4fd55-fdg85hg6"
  Error403:
      type: object
      properties:
        statusCode:
          type: string
          description: HTTP error code extension
          example: "6000"
        statusMessage:
          type: string
          description: "Short description of the error"
          example: "Forbidden"
        supportMessage:
          type: string
          description: "Longer description of the error"
          example: "Please verify token environment or access token or API key"
        transactionId:
          type: string
          description: "Id for tracing."
          example: "fg545f-cf4gg4fd55-fdg85hg6"
  Error404:
    type: object
    description: "Subscriber not found"
    properties:
      statusCode:
        type: string
        description: HTTP error code extension
        example: "1000"
      statusMessage:
        type: string
        example: "Not Found"
      supportMessage:
        type: string
        example: "Resource Not Found"
      transactionId:
        type: string
        description: "Id for tracing."
        example: "fg545f-cf4gg4fd55-fdg85hg6"
  Error405:
    type: object
    description: "Method not Allowed"
    properties:
      statusCode:
        type: string
        description: HTTP error code extension
        example: "4001"
      statusMessage:
        type: string
        example: "Not Allowed"
      supportMessage:
        type: string
        example: "Method Not Allowed"
      transactionId:
        type: string
        description: "Id for tracing."
        example: "fg545f-cf4gg4fd55-fdg85hg6"
  Error408:
    type: object
    properties:
      statusCode:
        type: string
        description: HTTP error code extension
        example: "3003"
      statusMessage:
        type: string
        description:  "The request timed out."
        example: "Timeout"
      supportMessage:
        type: string
        description: "The server took too long to respond."
        example: "Request timed out"
      transactionId:
        type: string
        description: "Id for tracing."
        example: "fg545f-cf4gg4fd55-fdg85hg6"
  Error415:
    type: object
    properties:
      statusCode:
        type: string
        description: HTTP error code extension
        example: "5000"
      statusMessage:
        type: string
        description: "Short description of the error"
        example: "Unsupported Media Type"
      supportMessage:
        type: string
        description: "Longer description of the error"
        example: "Unsupported Media Type. It should be application/json"
      transactionId:
        type: string
        description: "Id for tracing."
        example: "fg545f-cf4gg4fd55-fdg85hg6"
  Error500:
    type: object
    properties:
      statusCode:
        type: string
        description: HTTP error code extension
        example: "3001"
      statusMessage:
        type: string
        description: "Internal Server Error"
        example: "Internal Server Error"
      supportMessage:
        type: string
        description: "Error"
        example: "Internal Server Error"
      transactionId:
        type: string
        description: "Id for tracing."
        example: "fg545f-cf4gg4fd55-fdg85hg6"