




-- First update DD_MANDATE_REQUEST
UPDATE DD_MANDATE_REQUEST
   SET STATUS_CODE            = 1,
       STATUS_MESSAGE         = 'APPROVED',
       GATEWAY_STATUS_MESSAGE = '',
       RESPONSE_DATE          = '',
       LOG_ID                 = ''
 WHERE SYSTEM_REFERENCE_ID = '33dc7b67ed6b1b49ca1b9d73b28c2902';

-- Generate a new mandate id

-- Insert into DD_MANDATES from DD_MANDATE_REQUEST
INSERT INTO DD_MANDATES
  (MANDATE_ID,
   DD_CONFIG_DATE,
   MANDATE_REQ_ID,
   MERCHANT_ENTITY_ID,
   MERCHANT_REF_ID,
   MOBILE,
   NETWORK_ID,
   NARRATION,
   CURRENCY_ID,
   FREQUENCY_ID,
   NO_OF_INSTALLMENTS,
   START_DATE,
   END_DATE,
   DAY_OF_DEBIT,
   IS_PRE_AUTH_ENABLED,
   PLATFORM_SCHEDULING,
   OVA_SERVICE_ID,
   OVA_SP_ID,
   STATUS_CODE,
   STATUS_MESSAGE,
   SYSTEM_REFERENCE_ID,
   GATEWAY_REFERENCE_ID,
   GATEWAY_STATUS_MESSAGE,
   RESPONSE_DATE,
   FEE_TYPE_ID,
   FEE_TYPE_NAME,
   LAST_UPDATE,
   POST,
   LOG_ID)
  SELECT SEQ_DD_MANDATE_CONFIG.NEXTVAL, -- or P_DD_MANDATE_CONF_ID
         SYSDATE,
         REQUEST_ID,
         MERCHANT_ENTITY_ID,
         MERCHANT_REF_ID,
         MOBILE,
         NETWORK_ID,
         NARRATION,
         CURRENCY_ID,
         FREQUENCY_ID,
         NULL, -- NO_OF_INSTALLMENTS
         START_DATE,
         END_DATE,
         DAY_OF_DEBIT,
         1, -- IS_PRE_AUTH_ENABLED
         PLATFORM_SCHEDULING,
         OVA_SERVICE_ID,
         OVA_SP_ID,
         STATUS_CODE,
         STATUS_MESSAGE,
         SYSTEM_REFERENCE_ID,
         GATEWAY_REFERENCE_ID,
         GATEWAY_STATUS_MESSAGE,
         RESPONSE_DATE,
         FEE_TYPE_ID,
         FEE_TYPE_NAME,
         SYSDATE, -- LAST_UPDATE
         1, -- POST
         LOG_ID
    FROM DD_MANDATE_REQUEST
   WHERE SYSTEM_REFERENCE_ID = '33dc7b67ed6b1b49ca1b9d73b28c2902';
