CREATE OR REPLACE PROCEDURE GET_LIMITS_LIST_Filter(
    P_ENTITY_TYPE_NAME in varchar2 default null,
    P_LIMIT_TYPE_NAME in varchar2 default null,
    P_RESULT_CURSOR OUT SYS_REFCURSOR
) IS
BEGIN
    OPEN P_RESULT_CURSOR FOR
    SELECT
        E.ID,
        E.ENTITY_TYPE_ID,
        E.ACCOUNT_LEVEL_ID,
        E.LIMIT_TYPE_ID,
        E.MAX_BALANCE,
        E.MAX_OUTFLOW,
        E.MAX_INFLOW,
        E.IS_ACTIVE,
        ET.ENTITY_TYPE_NAME,
        AL.ACCOUNT_LEVEL_NAME,
        LT.LIMIT_TYPE_NAME
    FROM
        Entity_Account_Level_Limits E
    LEFT JOIN ENTITY_TYPE ET ON E.ENTITY_TYPE_ID = ET.ENTITY_TYPE_ID
    LEFT JOIN ACCOUNT_LEVEL AL ON E.ACCOUNT_LEVEL_ID = AL.ACCOUNT_LEVEL_ID
    LEFT JOIN LIMIT_TYPE LT ON E.LIMIT_TYPE_ID = LT.LIMIT_TYPE_ID;
     WHERE (P_ENTITY_TYPE_NAME IS NULL OR UPPER(ET.ENTITY_TYPE_NAME) = UPPER(P_ENTITY_TYPE_NAME))
            AND (P_LIMIT_TYPE_NAME IS NULL OR UPPER(LT.LIMIT_TYPE_NAME) = UPPER(P_LIMIT_TYPE_NAME));
    
END GET_LIMITS_LIST_Filter;
