MERCHANT_INTEGRATION_UTIL.FEEPAYMENT_VIA_3RDPARTYGW
BANK_INTEGRATION_UTIL.SET_3RDPRESPONSE_POST_PAYMENT


select * from V_ENTITY_WALLET_TOPUP_REQUEST where FEEPAYMENT_VIA3RDPARTY_TRANSID=56312528;  --return system_trans_id  ,if FEEPAYMENT_VIA3RDPARTY_TRANSID exit it means trnsaction already completed
select * from ENTITY_WALLET_TOPUP_REQUEST where SYSTEM_TRANS_ID=102952716;   --marked response from zenith with orderid or bankresponse
select * from ENTITY_FEEPAYMENT_VIA_3RDPARTY order by 1 desc;    --return TRANSACTION_ID created by endpoint "securepayment" and fetch by initate endpoint to confrim whetre transaction exit or not


SELECT  TRANSACTION_ID,TRANSACTION_DATE,MERCHANT_ENTITY_ID,ENTITY_ID,
WALLET_ID,BANK_ENTITY_ID,PAYMENT_MODE_ID,ENTITY_FIRST_NAME,ENTITY_MIDDLE_NAME,
ENTITY_LAST_NAME,MOBILE,EMAIL,ADDRESS1,ADDRESS2,CURRENCY_ID,AMOUNT_FCY,
X_TRANS_REF_CODE,POST,LOG_ID,GENERAL_PAYREQ_POS_TRANSID,SYSTEM_TRANS_ID
FROM ENTITY_FEEPAYMENT_VIA_3RDPARTY WHERE TRANSACTION_ID =56312534 ORDER BY TRANSACTION_ID;    --request saved and TRANSACTION_ID and SYSTEM_TRANS_ID returned by hitting csg ->   CSG/interapi/cardPayment

 w where w.FEEPAYMENT_VIA3RDPARTY_TRANSID=56312526;
