


select * from bank_register  where transaction_id=162255685;
SELECT * FROM SETTLEMENT_BANK_LST WHERE BANK_ENTITY_ID=149873;
BANK_ACCOUNT_ID
BULK_SETTLEMENT_UTIL_EXT.UPDATE_SETTLEMENT_SAVED_INSTRUC_GIPS
 
