select * from entity_api_credentials ec where ec.entity_id=149889;
select * from entity_system_config e where e. config_id=1239;
SELECT * from PAYMENT_MODE_ENTITY_CONFIG pm where pm.merchant_entity_id=149889;
SELECT * from V_PAYMENT_MODE_ENTITY_CONFIG pm where pm.merchant_entity_id=149889;
select * from payment_mode_entity_matrix order by 1  desc;
select * from payment_mode_entity_matrix e where e.entity_id=149889;
SELECT * from PAYMENT_MODE_ENTITY_CONFIG order by 1 desc;
SELECT * from V_PAYMENT_MODE_ENTITY_CONFIG order by 1 desc;
select * from entity e where e.entity_id=45159;


insert into payment_mode_entity_matrix (RULE_ID, ENTITY_ID, PAYMENT_MODE_ID, REMARKS, POST, LOG_ID, SETTLEMENT_DAYS_COUNT, IS_MULTI_CURRENCY_ENABLED, DOES_SUPPORT_UNSECURED_CARD, IS_UNSECURE_PAYMENT_ENABLED, IS_REVERSAL_ENABLED, PM_TRANSACTION_AMOUNT_CAP, PM_COMMISSION_AMOUNT_CAP, IS_AUTO_SETTLEMENT_ENABLED, IS_PREPARE_SETLMNT_INSTRUCTION, PM_BANK_COMMISSION_PERCENT, PM_BANK_COMM_CARDINT_PERCENT)
values (36, 131153, 1, 'PAYSTACK,VISA', 1, 0, 3, 0, 0, 1, 1, null, null, 0, 0, 2.0000, 2.0000);

insert into payment_mode_entity_matrix (RULE_ID, ENTITY_ID, PAYMENT_MODE_ID, REMARKS, POST, LOG_ID, SETTLEMENT_DAYS_COUNT, IS_MULTI_CURRENCY_ENABLED, DOES_SUPPORT_UNSECURED_CARD, IS_UNSECURE_PAYMENT_ENABLED, IS_REVERSAL_ENABLED, PM_TRANSACTION_AMOUNT_CAP, PM_COMMISSION_AMOUNT_CAP, IS_AUTO_SETTLEMENT_ENABLED, IS_PREPARE_SETLMNT_INSTRUCTION, PM_BANK_COMMISSION_PERCENT, PM_BANK_COMM_CARDINT_PERCENT)
values (35, 131153, 2, 'PAYSTACK,MASTER', 1, 0, 3, 0, 0, 1, 1, null, null, 0, 0, 2.0000, 2.0000);

select * from ENTITY_FEEPAYMENT_VIA_3RDPARTY order by 1 desc;
