SELECT MN.MOBILE_NETWORK_CODE, MNCR.* FROM MOBILE_NETWORK MN, MOBILE_NETWORK_CODE_PREFIX MNCR WHERE MN.MOBILE_NETWORK_ID = MNCR.MOBILE_NETWORK_ID;

SELECT LTRIM(GPRP.PAYEE_MOBILE,
             '+233'),
       SUBSTR(LTRIM(GPRP.PAYEE_MOBILE,
                    '+233'),
              1,
              2) NETWORK_CODE,
       GPRP.PAYEE_MOBILE,
       GPRP.*
  FROM GENERAL_PAYMENT_REQUEST_POS GPRP
 WHERE GPRP.TRANSACTION_DATE > ADD_MONTHS(SYSDATE,
                                          -5)
   AND SUBSTR(LTRIM(GPRP.PAYEE_MOBILE,
                    '+233'),
              1,
              2) IN ('20',
                     '50')
 ORDER BY 4 DESC;
-- collections search 
SELECT EFV.MOBILE,
       EFV.SYSTEM_TRANS_ID,
       VEWTR.TRANSACTION_DATE,
       VEWTR.BANK_ENTITY_ID,
       VEWTR.ENTITY_ID,
       EFV.MERCHANT_ENTITY_ID,
       VEWTR.STATUS_CODE,
       VEWTR.OVA_SERVICEID,
       VEWTR.BANK_RESPONSE_TEXT,
       EFV.POSTED_TO_MAIN_ENTITY,
       EFV.MERCHANT_RESPONSE_TEXT,
       EFV.MERCHANT_TRANSACTION_DATE,
       GPRP.*
  FROM ENTITY_WALLET_TOPUP_REQUEST VEWTR
 INNER JOIN ENTITY_FEEPAYMENT_VIA_3RDPARTY EFV
    ON VEWTR.FEEPAYMENT_VIA3RDPARTY_TRANSID = EFV.TRANSACTION_ID
 INNER JOIN GENERAL_PAYMENT_REQUEST_POS GPRP
    ON EFV.GENERAL_PAYREQ_POS_TRANSID = GPRP.TRANSACTION_ID
----inner join entity e on e.entity_id = efv.merchant_entity_id
--inner join direct_debit_term_structure ddts on ddts.transaction_id = efv.dd_termstruct_trans_id
--inner join direct_debit_request ddr on ddr.transaction_id = ddts.ddreq_trans_id
 WHERE VEWTR.TRANSACTION_DATE >=
       TO_DATE('24/01/2023',
               'dd/mm/yyyy')
   AND VEWTR.TRANSACTION_DATE <
       TO_DATE('25/01/2023',
               'dd/mm/yyyy')
      --and vewtr.status_code in (2)
      --and vewtr.bank_entity_id  = 43035 -- airtel 37135, 43035 MTN, vodafone 55851
      --and vewtr.ova_serviceid = 'EPSaham.sp'
      --and efv.system_trans_id = 99156123
      --and efv.posted_to_main_entity = 1
   AND EFV.MERCHANT_ENTITY_ID IN (77357)
--and gprp.txn_monitoring_status = 1
--and efv.fee_type_id = 1659
--and efv.dd_termstruct_trans_id is not null
--and vewtr.system_trans_id  in (106100140,106100142,106100139)  
--and efv.mobile = '+233244572483'
--and gprp.transaction_id = 50361663
-- and gprp.txn_monitoring_status is not null
-- and vewtr.bank_response_text like '%;;MTN Status Check%'
--and vewtr.bank_response_text like '%;;MTN Failesafe%'
--and gprp.merchant_trans_ref_code = 'RockzWaakye'
-- and vewtr.transaction_id in (54420365, 54421962, 54423592 ) 
 ORDER BY VEWTR.TRANSACTION_ID DESC; --92125180

GET_PENDING_3P_PAYMENTTXN

    SELECT * FROM ENTITY E WHERE E.ENTITY_ID = 149545;

SELECT * FROM FEE_TYPE FT WHERE FT.FEE_TYPE_ID = 351;
SELECT *
  FROM GENERAL_TRANSACTION_REQUEST GTR
 WHERE GTR.TRANSACTION_ID = 35106888;
SELECT *
  FROM PRE_AUTH_REQUEST EAR
 WHERE EAR.OVA_SERVICE_ID = 'EPSaham.sp'
 ORDER BY 1 DESC;

SELECT * FROM ENTITY_SYSTEM_CONFIG ORDER BY 1 DESC;

SELECT *
  FROM ENTITY_API_CREDENTIALS EAC
 WHERE EAC.ENTITY_ID = 55880
 ORDER BY 1 DESC;
SELECT * FROM MOBILE_NETWORK_OVA MNO WHERE MNO.MOBILE_NETWORK_ID = 3;
SELECT * FROM ENTITY_URL EU WHERE EU.MAIN_ENTITY_ID = 145658;
--epzenith.sp
--InterpU.sp
INSTOREOT.SP

IS_WORKING_TIME

    SELECT *
      FROM V_ENTITY_WALLET_TOPUP_REQUEST
     WHERE POSTED_TO_MAIN_ENTITY = 0
       AND MERCHANT_ENTITY_ID = 55880;
SELECT *
  FROM V_ENTITY_WALLET_TOPUP_REQUEST
 WHERE STATUS_CODE = 1
   AND POSTED_TO_MAIN_ENTITY = 0
   AND MERCHANT_ENTITY_ID = 62736
   AND TRANSACTION_DATE BETWEEN SYSDATE - 1 AND SYSDATE
   AND PAYMENT_MODE_ID IN (4);
SELECT *
  FROM V_ENTITY_WALLET_TOPUP_REQUEST
 WHERE STATUS_CODE = 1
   AND POSTED_TO_MAIN_ENTITY = 0
   AND MERCHANT_ENTITY_ID = 62736
   AND GENERAL_PAYREQ_POS_TRANSID IS NOT NULL
   AND TRANSACTION_DATE BETWEEN SYSDATE - 1 AND SYSDATE

    SELECT EE.*
            FROM V_ENTITY_WALLET_TOPUP_REQUEST EE
           WHERE STATUS_CODE = 1
             AND POSTED_TO_MAIN_ENTITY = 0
             AND MERCHANT_ENTITY_ID = 55778
             AND FEE_TYPE_ID = 351
             AND TRANSACTION_DATE BETWEEN SYSDATE - 10 AND SYSDATE
          
              SELECT *
                      FROM ENTITY_SYSTEM_CONFIG ESC
                     WHERE ESC.CONFIG_ID = 219;


SELECT * FROM ENTITY E WHERE E.ENTITY_CODE LIKE '%SAHAM%';

SELECT E.ENTITY_SHORT_NAME FROM ENTITY E WHERE E.ENTITY_ID = 108243;
UPDATE ENTITY E
   SET E.ENTITY_SHORT_NAME = 'Masco Foods Ltd KFC'
 WHERE E.ENTITY_ID = 108243;
SELECT * FROM ENTITY E WHERE E.ENTITY_SHORT_NAME LIKE '%(%';
GET_PENDING_3P_PAYMENTTXN

    SELECT *
      FROM JOB_CONFIGURATION JC
     WHERE JC.JOB_CODE = 'CHECK_MTN_TRANSACTIONS';
SELECT * FROM MOBILE_NETWORK_OVA TR WHERE TR.MOBILE_NETWORK_ID = 1;

UPDATE MOBILE_NETWORK_OVA OVA
   SET OVA.OVA_FRI_ID        = '+233547169801',
       OVA.OVA_MOBILE_NUMBER = '+233547169801'
 WHERE OVA.OVA_ID = 4;
OVA_UTIL.GET_OVA_LIST UPDATE MOBILE_NETWORK_OVA TR SET TR.OVA_FRI_ID = OVA_MOBILE_NUMBER WHERE TR.MOBILE_NETWORK_ID = 1;

{ "ProcessingNumber" :"99040201", "MOMTransactionID" :"19578403650", "StatusCode" :"01", "StatusDesc" :"{\" RECEIVERINFO ":{\" FROMFRI ":\" FRI :INTERPUL2.SP / USER ",\" STATUS ":\" SUCCESSFUL ",\" REFERENCEID ":\" 99040201 ",\" COMMUNICATIONCHANNEL ":null},\" TRANSACTIONID ":\" 19578403650 ",\" EXTERNALTRANSACTIONID ":\" 99040201 "}", "ThirdPartyAcctRef" :"99040201", "TransactionSuccessfull" :TRUE}

    SELECT *
      FROM ENTITY_SYSTEM_CONFIG ESC
     WHERE ESC.CONFIG_ID = 950
     ORDER BY 1 DESC;
UPDATE ENTITY_SYSTEM_CONFIG ESC
   SET ESC.CONFIG_VALUE = '-1;-2'
 WHERE ESC.CONFIG_ID = 950;
SELECT * FROM MOBILE_NETWORK_OVA MNO WHERE MNO.MOBILE_NETWORK_ID = 1;
SELECT *
  FROM JOB_CONFIGURATION JC
 WHERE JC.JOB_CODE IN ('CASHOUT_CONFLICTING_TRANSACTIONS',
                       'CHECK_MTN_TRANSACTIONS',
                       'TELCO_FAILSAFE_V2',
                       'CASHOUT_FAILSAFE');
UPDATE JOB_CONFIGURATION JC
   SET JC.ENABLED         = 0,
       JC.REQUIRES_UPDATE = 1
 WHERE JC.JOB_CODE IN ('CASHOUT_CONFLICTING_TRANSACTIONS',
                       'CHECK_MTN_TRANSACTIONS',
                       'TELCO_FAILSAFE_V2',
                       'CASHOUT_FAILSAFE');
PUBLIC CONST STRING CASHOUT_CONFLICTING_TRANSACTIONS = "CASHOUT_CONFLICTING_TRANSACTIONS";
PUBLIC CONST STRING CHECKMTNTRANSACTIONS = "CHECK_MTN_TRANSACTIONS";
PUBLIC CONST STRING TELCO_FAILSAFE_V2 = "TELCO_FAILSAFE_V2";
PUBLIC CONST STRING CASHOUT_FAILSAFE = "CASHOUT_FAILSAFE";
-- collections search 
SELECT GPRP.EXPIRY_DATE,
       GPRP.MERCHANT_TRANS_REF_CODE,
       EFV.MOBILE,
       EFV.SYSTEM_TRANS_ID,
       VEWTR.TRANSACTION_DATE,
       VEWTR.BANK_ENTITY_ID,
       VEWTR.ENTITY_ID,
       EFV.MERCHANT_ENTITY_ID,
       VEWTR.STATUS_CODE,
       VEWTR.BANK_RESPONSE_TEXT,
       EFV.POSTED_TO_MAIN_ENTITY,
       EFV.MERCHANT_RESPONSE_TEXT,
       EFV.MERCHANT_TRANSACTION_DATE,
       VEWTR.*
  FROM ENTITY_WALLET_TOPUP_REQUEST VEWTR
 INNER JOIN ENTITY_FEEPAYMENT_VIA_3RDPARTY EFV
    ON VEWTR.FEEPAYMENT_VIA3RDPARTY_TRANSID = EFV.TRANSACTION_ID
 INNER JOIN GENERAL_PAYMENT_REQUEST_POS GPRP
    ON EFV.GENERAL_PAYREQ_POS_TRANSID = GPRP.TRANSACTION_ID
--inner join entity e on e.entity_id = efv.merchant_entity_id
--inner join direct_debit_term_structure ddts on ddts.transaction_id = efv.dd_termstruct_trans_id
--inner join direct_debit_request ddr on ddr.transaction_id = ddts.ddreq_trans_id
 WHERE VEWTR.TRANSACTION_DATE >=
       TO_DATE('05/10/2022',
               'dd/mm/yyyy')
   AND VEWTR.TRANSACTION_DATE <
       TO_DATE('07/10/2022',
               'dd/mm/yyyy')
      --and vewtr.status_code = 1
      --and vewtr.bank_entity_id  = 43035 -- airtel 37135, 43035 MTN, vodafone 55851
      -- and vewtr.ova_spid = '2330110009469'
      --and efv.merchant_entity_id  = 55880
      --and gprp.txn_monitoring_status = 1
      --and efv.fee_type_id = 1659
      --and efv.dd_termstruct_trans_id is not null
      --and efv.system_trans_id  = 96532299  
   AND VEWTR.OVA_SERVICEID = 'InterpU.sp'
-- and gprp.txn_monitoring_status is not null
--and vewtr.bank_response_text like '%;;MTN Status Check%'
-- and gprp.merchant_trans_ref_code in ('5036715010121132','5045621010121862','5007251010119972')
 ORDER BY VEWTR.TRANSACTION_ID DESC; --92125180

SELECT * FROM TELCO_RESPONSE_CODE_MAPPING;
SELECT * FROM ENTITY_SYSTEM_CONFIG ORDER BY 1 DESC;
SELECT * FROM ENTITY_SYSTEM_CONFIG ORDER BY 1 DESC;
SELECT * FROM MOBILE_NETWORK_OVA;

UPDATE ENTITY_SYSTEM_CONFIG ESC
   SET ESC.CONFIG_VALUE = 'IPAYTEST;Ipaytest;UBAMERCHANT;UNITED BANK FOR AFRICA'
 WHERE ESC.CONFIG_ID = 1095;

UPDATE PAYMENT_MODE_ENTITY_OVA_CONFIG C
   SET C.OVA_SERVICEID = 'blupen.sp',
       C.OVA_SPID      = '2330110009469'
 WHERE C.PM_PROVIDER_ENTITY_ID = 43035
   AND C.MERCHANT_ENTTITY_ID = 55880;

SELECT * FROM MOBILE_NETWORK_OVA;
SELECT *
  FROM PAYMENT_MODE_ENTITY_OVA_CONFIG CC
 WHERE CC.MERCHANT_ENTTITY_ID = 108243;

SELECT *
  FROM PAYMENT_MODE_ENTITY_OVA_CONFIG CC
 WHERE CC.MERCHANT_ENTTITY_ID = 55880;

UPDATE PAYMENT_MODE_ENTITY_OVA_CONFIG C
   SET C.OVA_SERVICEID = 'interpul2.sp',
       C.OVA_SPID      = '2330110012889'
 WHERE C.PM_PROVIDER_ENTITY_ID = 43035
   AND C.MERCHANT_ENTTITY_ID = 55880;

SELECT E.ENTITY_SHORT_NAME FROM ENTITY E WHERE E.ENTITY_ID = 61052;

SELECT * FROM ENTITY_API_CREDENTIALS EAC WHERE EAC.ENTITY_ID = 61052;
UPDATE ENTITY_API_CREDENTIALS EAC
   SET EAC.APP_ID = '7453014226_blocked'
 WHERE EAC.ENTITY_ID = 61052;
{ "ProcessingNumber" :"98998293", "MOMTransactionID" :NULL, "StatusCode" :"100", "StatusDesc" :"Transaction couldn't be completed", "ThirdPartyAcctRef" :"98998293", "TransactionSuccessfull" :FALSE}

    SELECT MNO.OVA_SERVICEID,
           MNO.OVA_SPID,
           MNO.OVA_FRI_ID,
           MNO.OVA_MOBILE_NUMBER
      FROM MOBILE_NETWORK_OVA MNO
     WHERE MNO.MOBILE_NETWORK_ID = 1;
SELECT * FROM ENTITY_API_CREDENTIALS EAC WHERE EAC.ENTITY_ID = 55880;
SELECT * FROM SELECT * FROM ENTITY WHERE ENTITY_ID = 83787;

SELECT * FROM ENTITY_API_CREDENTIALS E WHERE E.ENTITY_ID = 83787;
SELECT * FROM ENTITY_API_CREDENTIALS EAC WHERE EAC.APP_ID = '7453014121';
SELECT * FROM ENTITY_URL EU WHERE EU.MAIN_ENTITY_ID = 135036;
--+233262689442

SELECT * FROM MERCHANT_TIN_CONFIG_FILE ORDER BY 1 DESC;

SELECT *
  FROM ENTITY_FEEPAYMENT_VIA_3RDPARTY EFV
 WHERE EFV.SYSTEM_TRANS_ID = 95649162;
SELECT * FROM BANK_REGISTER BR WHERE BR.SYSTEM_TRANS_ID = 95649162;

SELECT *
  FROM ENTITY_FEE_REGISTER EFG
 WHERE EFG.ENTITY_ID;

    SELECT * FROM ENTITY_SYSTEM_CONFIG WHERE CONFIG_ID = 745;

SELECT * FROM SMS_LOG SL WHERE SL.MAIN_ENTITY_ID = 134609 ORDER BY 1 DESC;
SELECT *
  FROM ENTITY_POS_CONFIG EPC
 WHERE EPC.ENTITY_ID = 134609
    OR EPC.ENTITY_ID IS NULL; --SEND_SMS_ON_PAYM_API_RESPONSE
SELECT * FROM ENTITY E WHERE E.ENTITY_CODE LIKE '%ACC1010000203%';
SELECT * FROM ENTITY_URL EU WHERE EU.MAIN_ENTITY_ID = 103230;
SELECT * FROM ENTITY E WHERE E.ENTITY_ID = 77357;
SELECT *
  FROM ENTITY
 WHERE ENTITY_CODE IN ('PRYMOLIMITED',
                       'PEGGHANA',
                       'PPT',
                       '148000000163927',
                       '1480281906');
SELECT *
  FROM GENERAL_PAYMENT_REQUEST_POS GPRP
 WHERE GPRP.TRANSACTION_DATE >=
       TO_DATE('01/07/2022',
               'dd/mm/yyyy')
   AND GPRP.TRANSACTION_DATE <
       TO_DATE('02/07/2022',
               'dd/mm/yyyy')
   AND GPRP.MERCHANT_ENTITY_ID = 77357
 ORDER BY GPRP.TRANSACTION_ID DESC;

SELECT * FROM MOBILE_NETWORK_OVA;

SELECT * FROM JOB_CONFIGURATION;

SELECT * FROM TRN_OPERATIONS TRO WHERE TRO.TRN_ID = 366;
SELECT * FROM ROLE_DETAIL RD WHERE RD.TRN_ID = 366;
SELECT *
  FROM ENTITY E
 WHERE E.ENTITY_CODE IN ('NHIA',
                         'ALWAYULMISAMIE');

SELECT *
  FROM V_ENTITY_WALLET_TOPUP_REQUEST EWTR
 WHERE EWTR.SYSTEM_TRANS_ID = 85034636;
SELECT * FROM ENTITY_POS_CONFIG EPC WHERE EPC.ENTITY_ID = 145700;

WEB_POS_UTIL.GET_ENTITY_POS_CONFIG_DETAILS
    SELECT *
      FROM PAYMENT_MODE_ENTITY_OVA_CONFIG CON
     WHERE CON.MERCHANT_ENTTITY_ID = 77265;

UPDATE PAYMENT_MODE_ENTITY_OVA_CONFIG CON
   SET CON.OVA_SERVICEID = 'Interpull.sp',
       CON.OVA_SPID      = '2330110004130'
 WHERE CON.MERCHANT_ENTTITY_ID = 77265;

UPDATE PAYMENT_MODE_ENTITY_OVA_CONFIG C
   SET C.OVA_SERVICEID = 'BoafoPa.sp',
       C.OVA_SPID      = '2330110014029'
 WHERE C.PM_PROVIDER_ENTITY_ID = 43035
   AND C.MERCHANT_ENTTITY_ID = 55880;

UPDATE PAYMENT_MODE_ENTITY_OVA_CONFIG C
   SET C.OVA_SERVICEID = 'BoafoPa.sp',
       C.OVA_SPID      = '2330110014029'
 WHERE C.PM_PROVIDER_ENTITY_ID = 43035
   AND C.MERCHANT_ENTTITY_ID = 55880;

SELECT * FROM ENTITY E WHERE E.ENTITY_ID = 77265;
SELECT * FROM MOBILE_NETWORK_OVA MNO WHERE MNO.MOBILE_NETWORK_ID = 1;

SUPPORT_PORTAL_UTIL.GET_COLLECTION_GRA_LISTING_PAGINATED

SYSTEM_PROCESS_UTIL.GET_PAYMODE_ENTITY_OVA_CONFIG PRE_AUTH_INSECUR_PYMT_CFG_UTIL.GET_MISCELLANEOUS_INFO

    SELECT *
      FROM FEE_TYPE FT
     WHERE FT.FEE_TYPE_ID IN (351,
                              1659);
{ "xml" :"version=\" 1.0 " encoding=\" UTF - 8 "", "ThirdPartyAcctRef" :"80738678", "ProcessingNumber" :"80738678", "SenderID" :"MOM", "StatusCode" :"1000", "StatusDesc" :"Pending", "MOMTransactionID" :NULL} { "xml" :"version=\" 1.0 " encoding=\" UTF - 8 "", "ThirdPartyAcctRef" :"80737705", "ProcessingNumber" :"80737705", "SenderID" :"MOM", "StatusCode" :"1000", "StatusDesc" :"Pending", "MOMTransactionID" :NULL}

{ "trans_id" :"MP220211.0004.C03187", "trans_ref" :"80408359", "message" :"You have entered an invalid PIN. your PIN should be numeric only. Kindly check and try again. Thank You.", "trans_status" :"00332", "TransactionSuccessfull" :FALSE}

    SELECT * FROM ENTITY E WHERE E.ENTITY_CODE = '135795';
SELECT * FROM USSD_MOBILE_WHITELISTING ORDER BY 1 DESC;

SELECT *
  FROM MOBILE_NETWORK_OVA MNO
 WHERE MNO.MOBILE_NETWORK_ID = 1
 ORDER BY 1 DESC;

SELECT * FROM MERCHANT_UAT_CONFIGURATION;

--58902
SELECT DDR.TRANSACTION_ID      AS DD_TRANS_ID,
       E.ENTITY_CODE           AS MERCHANT,
       MN.MOBILE_NETWORK_CODE  AS NETWORK,
       FT.FEE_TYPE_CODE,
       DDR.DEBTOR_MOBILE       AS MOBILE,
       DDR.INSTALLMENT_FREQ_ID,
       DDR.MONTHLY_AMOUNT      AS AMOUNT
  FROM DIRECT_DEBIT_REQUEST DDR,
       FEE_TYPE             FT,
       ENTITY               E,
       MOBILE_NETWORK       MN
 WHERE DDR.MERCHANT_ENTITY_ID = 58902
   AND DDR.DD_TRANS_STATUS_ID = 1
   AND DDR.MERCHANT_ENTITY_ID = E.ENTITY_ID
   AND DDR.FEE_TYPE_ID = FT.FEE_TYPE_ID
   AND DDR.MOBILE_NETWORK_ID = MN.MOBILE_NETWORK_ID
 ORDER BY DDR.MOBILE_NETWORK_ID DESC;

SELECT *
  FROM ENTITY E
 WHERE ENTITY_ID IN (145495,
                     75391,
                     134609,
                     107135,
                     102380,
                     89441,
                     80047,
                     75391,
                     67995,
                     58902);

SELECT * FROM FEE_TYPE WHERE FEE_TYPE_ID = 3122;
SELECT *
  FROM ENTITY_API_CREDENTIALS
 WHERE APP_ID = '7116022678'
 ORDER BY 1 DESC;
 
SELECT VEWTR.*
  FROM ENTITY_WALLET_TOPUP_REQUEST VEWTR
 INNER JOIN ENTITY_FEEPAYMENT_VIA_3RDPARTY EFV
    ON VEWTR.FEEPAYMENT_VIA3RDPARTY_TRANSID = EFV.TRANSACTION_ID
 WHERE VEWTR.TRANSACTION_DATE >=
       TO_DATE('16/09/2021',
               'dd/mm/yyyy')
   AND VEWTR.TRANSACTION_DATE <
       TO_DATE('18/09/2021',
               'dd/mm/yyyy')
   AND EFV.MERCHANT_ENTITY_ID = 77265
      --and gprp.wpos_trans_channel_id = 9
      --and vewtr.payment_mode_id = 9
      --and efv.system_trans_id = 63174260
      --and efv.dd_termstruct_trans_id is not null
   AND EFV.BANK_ENTITY_ID = 55851
--and vewtr.status_code = 1 
--and gprp.voucher_number is not null
 ORDER BY VEWTR.SYSTEM_TRANS_ID DESC;

SELECT * FROM ENTITY WHERE ENTITY_ID = 37135;

SELECT *
  FROM GENERAL_PAYMENT_REQUEST_POS GP
 WHERE GP.VOUCHER_NUMBER IS NOT NULL
 ORDER BY 1 DESC;

SELECT *
  FROM V_GENERAL_PAYMENT_REQUEST_POS VEWTR
 WHERE POST = 1
      
   AND VEWTR.TRANSACTION_DATE >=
       TO_DATE('01/09/2021',
               'dd/mm/yyyy')
   AND VEWTR.TRANSACTION_DATE <
       TO_DATE('16/09/2021',
               'dd/mm/yyyy')
   AND VEWTR.VOUCHER_NUMBER IS NOT NULL
 ORDER BY 1 DESC;

-- uiel098vx1

SELECT * FROM ENTITY WHERE ENTITY_CODE = 'NHIA';
SELECT * FROM PAYMENT_MODE;

SELECT * FROM MOBILE_NETWORK;

SELECT * FROM ENTITY_URL EU WHERE EU.MAIN_ENTITY_ID = 55880;
--45159
SELECT M.MERCHANT_ENTITY_ID
  FROM PAYMENT_MODE_ENTITY_CONFIG M
 WHERE M.PM_PROVIDER_ENTITY_ID = 45159
    SELECT * FROM ENTITY WHERE ENTITY_ID = 135036;


SELECT *
  FROM ENTITY
 WHERE ENTITY_ID IN (SELECT M.MERCHANT_ENTITY_ID
                       FROM PAYMENT_MODE_ENTITY_CONFIG M
                      WHERE M.PM_PROVIDER_ENTITY_ID = 45159);
SELECT * FROM ENTITY_API_CREDENTIALS EAC WHERE EAC.APP_ID = '5892306303';
SELECT *
  FROM ENTITY_FEEPAYMENT_VIA_3RDPARTY F
 WHERE F.SYSTEM_TRANS_ID IN (56846717);

-- collection momo ussd 

SELECT * FROM ENTITY E WHERE E.ENTITY_CODE = 'BLU000000001333';
SELECT *
  FROM MICROFIN_TRANSACTION MT
 WHERE MT.MERCHANT_ENTITY_ID = 101941
 ORDER BY 1 DESC;
SELECT *
  FROM MICROFIN_TRANSACTION_DET MTD
 WHERE MTD.MICROFIN_TRANS_ID IN (4325,
                                 4323,
                                 4324)
 ORDER BY 1 DESC;

SELECT SUM(RR.AMOUNT_FCY)
  FROM REMITTANCE_REGISTER RR
 WHERE RR.MAIN_ENTITY_ID = 101941
      --  datetime.now.date
      --  datetime.now.adddays(1).date
   AND RR.TRANSACTION_DATE >= TO_DATE('12/09/2021',
                                      'dd/mm/yyyy')
   AND RR.TRANSACTION_DATE < TO_DATE('13/09/2021',
                                     'dd/mm/yyyy')
   AND RR.PAYOUT_BANK_ACCOUNT_NO = '5330503001047'
   AND RR.STATUS_CODE = 1;

-- direct debit collections 
SELECT * FROM ENTITY WHERE ENTITY_CODE = 'SAHAMLIFE';
SELECT *
  FROM ENTITY
 WHERE ENTITY_ID IN (SELECT M.MERCHANT_ENTITY_ID
                       FROM PAYMENT_MODE_ENTITY_CONFIG M
                      WHERE M.PM_PROVIDER_ENTITY_ID = 45159);

SELECT VEWTR.*,
       EFV.*
  FROM ENTITY_WALLET_TOPUP_REQUEST VEWTR
 INNER JOIN ENTITY_FEEPAYMENT_VIA_3RDPARTY EFV
    ON VEWTR.FEEPAYMENT_VIA3RDPARTY_TRANSID = EFV.TRANSACTION_ID
--inner join  general_payment_request_pos gprp on efv.general_payreq_pos_transid = gprp.transaction_id
 WHERE
--  vewtr.TRANSACTION_DATE >=  TO_DATE('06/09/2021','dd/mm/yyyy')
-- AND vewtr.TRANSACTION_DATE <  TO_DATE('07/09/2021','dd/mm/yyyy')
 EFV.MERCHANT_ENTITY_ID = 89441
--and gprp.wpos_trans_channel_id = 9
--and vewtr.payment_mode_id = 9
 AND EFV.SYSTEM_TRANS_ID = 63394470
 ORDER BY VEWTR.SYSTEM_TRANS_ID DESC;

SELECT DDR.TRANSACTION_ID,
       DDR.DEBTOR_CODE,
       DDR.DD_TRANS_STATUS_ID,
       DDR.TRANSACTION_DATE,
       DDR.DEBTOR_MOBILE
  FROM DIRECT_DEBIT_REQUEST DDR
 WHERE DDR.MERCHANT_ENTITY_ID = 89441
   AND DDR.DEBTOR_MOBILE IN ('+233543808095')
 ORDER BY 1 DESC;

SELECT *
  FROM DIRECT_DEBIT_TERM_STRUCTURE DDTS
 WHERE DDTS.DDREQ_TRANS_ID IN
       (SELECT DDR.TRANSACTION_ID
          FROM DIRECT_DEBIT_REQUEST DDR
         WHERE DDR.MERCHANT_ENTITY_ID = 89441
           AND DDR.DEBTOR_MOBILE IN ('+233543808095'))
 ORDER BY 1 DESC;

SELECT *
  FROM DIRECT_DEBIT_ENTITY_CONFIG DDEC
 WHERE DDEC.MAIN_ENTITY_ID = 89441;
SELECT *
  FROM ENTITY_FEEPAYMENT_VIA_3RDPARTY EFV
 WHERE EFV.MERCHANT_ENTITY_ID = 89441
   AND EFV.DD_TERMSTRUCT_TRANS_ID IN (3422796);
