--system config


insert into entity_system_config (CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_STATUS)
values (1279, 'YOGUPAY_CLIENT_URL', 'https://localhost:5001/api/Payout/CreatePayout', 'YOGUPAY MICROSERVICE URL');



insert into entity_system_config (CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_STATUS)
values (1280, 'YOGUPAY_CLIENT_USERNAME', 'Yogupay', 'YOGUPAY MICROSERVICE AUTH USERNAME');


insert into entity_system_config (CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_STATUS)
values (1281, 'YOGUPAY_CLIENT_PASSWORD', '5!02%!89!3', 'YOGUPAY MICROSERVICE AUTH PASSWORD');

insert into entity_system_config (CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_STATUS)
values (1282, 'YOGUPAY_ENTITY_ID', '150378', 'YOGUPAY ENTITYID');



--processor entity create


insert into entity
  (ENTITY_ID,
   ENTITY_CODE,
   ENTITY_TYPE_ID,
   ENTITY_FIRST_NAME,
   ENTITY_MIDDLE_NAME,
   ENTITY_LAST_NAME,
   REGISTRATION_DATE,
   ENTITY_NATURE_ID,
   MALE_OR_FEMALE,
   MOBILE,
   PHONE1,
   PHONE2,
   FAX1,
   FAX2,
   EMAIL,
   POST,
   LOG_ID,
   ADDRESS1,
   ADDRESS2,
   CITY_ID,
   PREFERRED_CLEARING_ENTITY,
   REGION_ID,
   COUNTRY_ID,
   OTHER_MOBILE,
   CITY_NAME,
   POSTAL_CODE,
   IMAGE_NAME,
   BIRTH_DATE,
   AUTO_CREATED,
   IS_SMS_ENABLED,
   IS_EMAIL_ENABLED,
   ACCEPT_MULTIPAYMENTS_VIA_OTC,
   IS_MULTI_CURRENCY_ENABLED,
   ENTITY_CATEGORY_ID,
   IS_GROUP_SMS_ENABLED,
   CONTACT_PERSON_FIRST_NAME,
   CONTACT_PERSON_EMAIL,
   ENTITY_SETUP_DET_ID,
   IS_GROUP_EMAIL_ENABLED,
   IMAGE_NAME_OPENMERCHALL_PAGE,
   CONTACT_PERSON_MIDDLE_NAME,
   CONTACT_PERSON_LAST_NAME,
   HIDE_SURCHARGE_COMMISSION,
   ENTITY_SHORT_NAME,
   IS_INTERPAY_PARTNER,
   IS_SUB_MERCHANT_REQUIRED,
   PARENT_ENTITY_ID,
   MINIMUM_COMMISSION_PERCENT,
   CSS_FILE_NAME,
   IS_UNSECURE_PAYMENT_ENABLED,
   SMALL_IMAGE_NAME,
   IS_PRE_AUTH_ENABLED,
   PARENT_SETTLMNT_BANKACC,
   INITIATOR_IMEI_NO,
   INITIATOR_DEVICE_ID,
   PIN,
   NOTIFICATION_EMAIL,
   INTERPAY_MIN_COMM_VALUE,
   ACCOUNT_MANAGER_ID,
   AGENT_SETUP_DET_ROW_ID,
   PARTNER_MERCHANT_BANK_ID,
   IS_COMMISSION_SPLIT_ENABLED,
   IS_PARTNER_BANK_REQUIRED,
   CLIENT_TIMESTAMP,
   PAYMODE_ENTITY_PROMPT_CODE,
   IS_CUSTOMER_EMAIL_ENABLED,
   IS_INWARD_REMITTANCE_PARTNER,
   FACEBOOK_LINK,
   INSTAGRAM_LINK,
   TWITTER_LINK)
values
  (150378,
   'YOGUPAY',
   2,
   'YOGUPAY',
   null,
   null,
   to_date('29-05-2025 12:05:11', 'dd-mm-yyyy hh24:mi:ss'),
   1,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   1,
   0,
   null,
   null,
   null,
   null,
   null,
   1,
   null,
   'Abuja',
   null,
   null,
   null,
   0,
   0,
   0,
   0,
   0,
   3,
   0,
   null,
   null,
   null,
   0,
   null,
   null,
   null,
   0,
   'YOGUPAY',
   1,
   0,
   null,
   null,
   null,
   0,
   null,
   0,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   null,
   0,
   0,
   null,
   null,
   1,
   0,
   null,
   null,
   null);






--remit entity process config 

insert into REMIT_ENTITY_PROCESS_CONFIG (MERCHANT_ENTITY_ID, PM_PROVIDER_ENTITY_ID, ISENABLED, POST, LOG_ID, PAYOUT_TYPE_ID, NETWORK_ENTITY, DESCRIPTION,CURRENCY_ID)
values (149807, 150378, 1, 1, 11920834, 2, 43035, 'YOGUPAY,MTN',79);

insert into  REMIT_ENTITY_PROCESS_CONFIG (MERCHANT_ENTITY_ID, PM_PROVIDER_ENTITY_ID, ISENABLED, POST, LOG_ID, PAYOUT_TYPE_ID, NETWORK_ENTITY, DESCRIPTION,CURRENCY_ID)
values (149807, 150378, 1, 1, 11920834, 2, 37135, 'YOGUPAY,AIRTELTIGO',79);

insert into REMIT_ENTITY_PROCESS_CONFIG (MERCHANT_ENTITY_ID, PM_PROVIDER_ENTITY_ID, ISENABLED, POST, LOG_ID, PAYOUT_TYPE_ID, NETWORK_ENTITY, DESCRIPTION,CURRENCY_ID)
values (149807, 150378, 1, 1, 11920834, 2, 55851, 'YOGUPAY,VODAFONE',79);




