select  * from ACCOUNT_SIGNUP;
 drop table ACCOUNT_SIGNUP;
select * from ACCOUNT_SIGNUP;
select * from ADMIN_PORTAL_USERS;

drop table ACCOUNT_SIGNUP;

-- Create table
create table ACCOUNT_SIGNUP
(
  row_id                 NUMBER generated by default as identity,
  mobile_no              VARCHAR2(15),
  country_id             NUMBER,
  notification_enable    NUMBER default 0,
  residence_country      NUMBER,
  card_type              NUMBER default 0,
  first_name             NVARCHAR2(50),
  last_name              NVARCHAR2(50),
  father_name            NVARCHAR2(50),
  gender                 NVARCHAR2(1),
  phone_number           VARCHAR2(15),
  birth_place            NVARCHAR2(50),
  address                NVARCHAR2(500),
  dob                    DATE,
  email                  NVARCHAR2(50),
  occupation             NUMBER,
  monthly_income         NUMBER,
  sof                    NUMBER,
  is_profile_active      NUMBER default 0,
  creation_date          TIMESTAMP(6),
  msisdn                 NUMBER(20),
  entity_id              NUMBER(12),
  last_update            TIMESTAMP(6),
  assentify_card_url     NVARCHAR2(500),
  assentify_selfee_score NUMBER,
  is_selfie_verified     NUMBER,
  is_profile_completed   NUMBER,
  is_pin_created         NUMBER default 0,
  entity_type_id         NUMBER(12),
  bank_id                NUMBER(12),
  bank_branch_id         NUMBER(12),
  account_no             VARCHAR2(30),
  user_name              VARCHAR2(50),
  password               VARCHAR2(50)
)
tablespace USERS
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
-- Create/Recreate primary, unique and foreign key constraints 
alter table ACCOUNT_SIGNUP
  add constraint SIGNUP_ROWID_PK primary key (ROW_ID)
  using index 
  tablespace USERS
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table ACCOUNT_SIGNUP
  add constraint MOBILE_UK unique (MOBILE_NO)
  using index 
  tablespace USERS
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table ACCOUNT_SIGNUP
  add constraint FK_SIGNUP_ENTITY foreign key (ENTITY_ID)
  references ENTITY (ENTITY_ID);


