1st step 


CREATE OR REPLACE PACKAGE CONSUMER_PROFILE_UTIL AS
                                                    
PROCEDURE UPDATE_CONSUMER_PROFILE(
    P_ENTITY_ID      IN NUMBER,
    P_FIRST_NAME     IN VARCHAR2,
    P_LAST_NAME      IN VARCHAR2,
    P_DOB            IN DATE,
    P_EMAIL          IN VARCHAR2,
    P_COUNTRY_ID     IN NUMBER,
    P_OCCUPATION     IN NUMBER,
    P_MONTHLY_INCOME IN NUMBER,
    P_SOF            IN NUMBER,
    P_LEGAL_ID       IN NUMBER,
    P_PERSON_NAME    IN VARCHAR2,
    P_TRADE_NAME     IN VARCHAR2,
    P_LEGAL_NAME     IN VARCHAR2,
    P_DOMAIN         IN VARCHAR2,
    P_REGISTER_NUMBER   IN VARCHAR2,
    P_REGISTER_CERTIFICATE IN VARCHAR2,
    P_COUNTRY_INCORPORATION   IN VARCHAR2,
    P_CERTIFICATE_INCORPORATION  IN VARCHAR2,
    P_AUTHENTICATED_ARTICLES IN VARCHAR2,
    P_COMMERCIAL_CIRCULAR    IN VARCHAR2,
    P_DESIGNATION            IN VARCHAR2,
    P_NO_OF_OUTLETS          IN VARCHAR2,
    P_SIGNATORY_NAME         IN VARCHAR2,
    P_BUSINESS_TYPE          IN VARCHAR2,
    P_DESCRIPTION_GOODS      IN VARCHAR2,
    P_COUNTRY_ACTIVE         IN VARCHAR2,
    P_TAX_NO                 IN VARCHAR2,
    P_MERCHANT_DISCOUNT_RATES   IN VARCHAR2,
    P_INCORPORATION_DATE IN DATE,
    P_ADDRESS                 IN VARCHAR2,
    ---P_PASSWORD       IN VARCHAR2,
    P_STATUS_CODE    OUT NUMBER,
    P_STATUS_MESSAGE OUT VARCHAR2
);

PROCEDURE GET_CONSUMER_PROFILE(
    P_ENTITY_ID      IN NUMBER,
    P_ENTITY_TYPE_ID IN NUMBER,
    P_RESULT_CURSOR  OUT SYS_REFCURSOR
);

END CONSUMER_PROFILE_UTIL;


-> 2nd step 


CREATE OR REPLACE PACKAGE BODY CONSUMER_PROFILE_UTIL AS
  
  ----------------------------------------------------------------
  ----------------------UPDATE_CONSUMER_PROFILE----------------------
  ----------------------------------------------------------------
  PROCEDURE UPDATE_CONSUMER_PROFILE(
    P_ENTITY_ID      IN NUMBER,
    P_FIRST_NAME     IN VARCHAR2,
    P_LAST_NAME      IN VARCHAR2,
    P_DOB            IN DATE,
    P_EMAIL          IN VARCHAR2,
    P_COUNTRY_ID     IN NUMBER,
    P_OCCUPATION     IN NUMBER,
    P_MONTHLY_INCOME IN NUMBER,
    P_SOF            IN NUMBER,
    P_LEGAL_ID       IN NUMBER,
    P_PERSON_NAME    IN VARCHAR2,
    P_TRADE_NAME     IN VARCHAR2,
    P_LEGAL_NAME     IN VARCHAR2,
    P_DOMAIN         IN VARCHAR2,
    P_REGISTER_NUMBER   IN VARCHAR2,
    P_REGISTER_CERTIFICATE IN VARCHAR2,
    P_COUNTRY_INCORPORATION   IN VARCHAR2,
    P_CERTIFICATE_INCORPORATION  IN VARCHAR2,
    P_AUTHENTICATED_ARTICLES IN VARCHAR2,
    P_COMMERCIAL_CIRCULAR    IN VARCHAR2,
    P_DESIGNATION            IN VARCHAR2,
    P_NO_OF_OUTLETS          IN VARCHAR2,
    P_SIGNATORY_NAME         IN VARCHAR2,
    P_BUSINESS_TYPE          IN VARCHAR2,
    P_DESCRIPTION_GOODS      IN VARCHAR2,
    P_COUNTRY_ACTIVE         IN VARCHAR2,
    P_TAX_NO                 IN VARCHAR2,
    P_MERCHANT_DISCOUNT_RATES   IN VARCHAR2,
    P_INCORPORATION_DATE IN DATE,
    P_ADDRESS                 IN VARCHAR2,
    ---P_PASSWORD       IN VARCHAR2,
    P_STATUS_CODE    OUT NUMBER,
    P_STATUS_MESSAGE OUT VARCHAR2
) IS
BEGIN
    -- UPDATE ENTITY TABLE
    UPDATE ENTITY
    SET ENTITY_FIRST_NAME = P_FIRST_NAME,
        ENTITY_LAST_NAME = P_LAST_NAME,
        --MALE_OR_FEMALE = P_GENDER,
        BIRTH_DATE = P_DOB,
        ENTITY_SHORT_NAME = P_FIRST_NAME
    WHERE ENTITY_ID = P_ENTITY_ID;

    -- UPDATE ENTITY_ACCOUNT TABLE
    --UPDATE ENTITY_ACCOUNT
    --SET MSISDN = P_MOBILE_NUMBER
    --WHERE ENTITY_ID = P_ENTITY_ID;

    -- UPDATE ENTITY_WALLET TABLE (USD WALLET)
    --UPDATE ENTITY_WALLET
    --SET WALLET_CODE = P_WALLET_CODE
    --WHERE ENTITY_ACCOUNT_ID = (SELECT ENTITY_ACCOUNT_ID FROM ENTITY_ACCOUNT WHERE ENTITY_ID = P_ENTITY_ID)
    --  AND CURRENCY_ID = 2; -- CURRENCY ID FOR USD

    -- UPDATE ENTITY_WALLET TABLE (LBP WALLET)
    --UPDATE ENTITY_WALLET
    --SET WALLET_CODE = P_WALLET_CODE
    --WHERE ENTITY_ACCOUNT_ID = (SELECT ENTITY_ACCOUNT_ID FROM ENTITY_ACCOUNT WHERE ENTITY_ID = P_ENTITY_ID)
     -- AND CURRENCY_ID = 34; -- CURRENCY ID FOR LBP

    -- UPDATE ENTITY_CONTACT TABLE
    UPDATE ENTITY_CONTACT
    SET --MOBILE = P_MOBILE_NUMBER,
        EMAIL = P_EMAIL,
        CONTACT_PERSON_FIRST_NAME = P_FIRST_NAME,
        CONTACT_PERSON_EMAIL = P_EMAIL
    WHERE ENTITY_ID = P_ENTITY_ID;

    -- UPDATE ENTITY_ACCOUNT_PROFILE TABLE
    UPDATE ENTITY_ACCOUNT_PROFILE
    SET FIRST_NAME = P_FIRST_NAME,
        FAMILY_NAME = P_LAST_NAME,
        DATE_OF_BIRTH = P_DOB,
        --GENDER = P_GENDER,
        PRIMARY_COUNTRY_ID = P_COUNTRY_ID,
        OCCUPATION_ID = P_OCCUPATION,
        AVERAGE_MONTHLY_INCOME_ID = P_MONTHLY_INCOME,
        SOURCE_OF_FUNDS_ID = P_SOF,
        EMAIL = P_EMAIL
    WHERE ENTITY_ACCOUNT_ID = (SELECT ENTITY_ACCOUNT_ID FROM ENTITY_ACCOUNT WHERE ENTITY_ID = P_ENTITY_ID);

    -- UPDATE ACCOUNT_SIGNUP TABLE
    UPDATE ACCOUNT_SIGNUP
    SET first_name = P_FIRST_NAME,
        last_name = P_LAST_NAME,
        --gender = P_GENDER,
        dob = P_DOB,
        email = P_EMAIL,
        country_id = P_COUNTRY_ID,
        occupation = P_OCCUPATION,
        monthly_income = P_MONTHLY_INCOME,
        sof = P_SOF
        --password = P_PASSWORD
    WHERE entity_id = P_ENTITY_ID;

    -- UPDATE MOJO_USER_PROFILE TABLE
    UPDATE MOJO_USER_PROFILE
    SET LEGAL_ID = P_LEGAL_ID,   
    PERSON_NAME = P_PERSON_NAME,
    TRADE_NAME = P_TRADE_NAME,
    LEGAL_NAME = P_LEGAL_NAME,
    WEBSITE_DOMAIN = P_DOMAIN,
    REGISTER_NUMBER= P_REGISTER_NUMBER,
    REGISTER_CERTIFICATE=P_REGISTER_CERTIFICATE,
    COUNTRY_OF_INCORPORATION=P_COUNTRY_INCORPORATION,
    CERTIFICATE_OF_INCORPORATION=P_CERTIFICATE_INCORPORATION,
    DULY_AUTHENTICATED_ARTICLES=P_AUTHENTICATED_ARTICLES,
    COMMERCIAL_CIRCULAR=P_COMMERCIAL_CIRCULAR,
    CONTACT_DESIGNATION=P_DESIGNATION,
    NUMBER_OUTLETS=P_NO_OF_OUTLETS,
    AUTHORIZED_SIGNATORY_NAME=P_SIGNATORY_NAME,
    BUSINESS_TYPE=P_BUSINESS_TYPE,
    DESCRIPTION_OF_GOODS=P_DESCRIPTION_GOODS,
    COUNTRY_OF_ACTIVITY=P_COUNTRY_ACTIVE,
    TAX_NO=P_TAX_NO,
    MERCHANT_DISCOUNT_RATES = P_MERCHANT_DISCOUNT_RATES,
    INCORPORATION_DATE =P_INCORPORATION_DATE,
    UPDATED_DATE = SYSDATE,
    ADDRESS = P_ADDRESS
    
    WHERE entity_id = P_ENTITY_ID;
    
    -- UPDATE USERS TABLE
    --UPDATE USERS
    --SET
    --    PASSWORD = P_PASSWORD
    --WHERE ENTITY_ID = P_ENTITY_ID AND USER_NAME = P_MOBILE_NUMBER;

    COMMIT;
    P_STATUS_CODE := 1;
EXCEPTION
    WHEN OTHERS THEN
        -- ROLLBACK THE TRANSACTION IF ANY ERROR OCCURS
        ROLLBACK;
        -- RAISE THE EXCEPTION AGAIN TO PROPAGATE THE ERROR
        P_STATUS_CODE := 0;
        P_STATUS_MESSAGE := SQLERRM;
END UPDATE_CONSUMER_PROFILE;


  ----------------------------------------------------------------
    ----------------------GET_CONSUMER_PROFILE---------------------
  ----------------------------------------------------------------
  PROCEDURE GET_CONSUMER_PROFILE(
    P_ENTITY_ID      IN NUMBER,
    P_ENTITY_TYPE_ID IN NUMBER,
    P_RESULT_CURSOR  OUT SYS_REFCURSOR
) IS
BEGIN
    OPEN P_RESULT_CURSOR FOR
     SELECT
        E.ENTITY_ID,
        E.ENTITY_CODE,
        E.ENTITY_FIRST_NAME,
        E.ENTITY_LAST_NAME,
        E.MALE_OR_FEMALE AS GENDER,
        E.BIRTH_DATE AS DOB,
        E.REGISTRATION_DATE,
        --E.ENTITY_NATURE_ID AS COUNTRY_ID,
        EA.MSISDN AS MOBILE_NUMBER,
        EC.EMAIL,
        --EC.CONTACT_PERSON_FIRST_NAME,
        --EC.CONTACT_PERSON_EMAIL AS CONTACT_EMAIL,
        --EA.POST AS ENTITY_ACCOUNT_STATUS,
        --EAP.FIRST_NAME AS PROFILE_FIRST_NAME,
        --EAP.FAMILY_NAME AS PROFILE_LAST_NAME,
        --EAP.DATE_OF_BIRTH AS PROFILE_DOB,
        --EAP.GENDER AS PROFILE_GENDER,
        EAP.Primary_Country_Id AS PROFILE_COUNTRY_ID,
        EAP.OCCUPATION_ID,
        EAP.AVERAGE_MONTHLY_INCOME_ID,
        EAP.SOURCE_OF_FUNDS_ID,
        MP.LEGAL_ID,
        MP.PERSON_NAME,
        MP.TRADE_NAME,
        MP.LEGAL_NAME,
        MP.WEBSITE_DOMAIN,
        MP.REGISTER_NUMBER,
        MP.REGISTER_CERTIFICATE,
        MP.COUNTRY_OF_INCORPORATION,
        MP.CERTIFICATE_OF_INCORPORATION,
        MP.DULY_AUTHENTICATED_ARTICLES,
        MP.COMMERCIAL_CIRCULAR,
        MP.CONTACT_DESIGNATION,
        MP.NUMBER_OUTLETS,
        MP.AUTHORIZED_SIGNATORY_NAME,
        MP.BUSINESS_TYPE,
        MP.DESCRIPTION_OF_GOODS,
        MP.COUNTRY_OF_ACTIVITY,
        MP.TAX_NO,
        MP.INCORPORATION_DATE,
        MP.MERCHANT_DISCOUNT_RATES,
        MP.CREATED_DATE,
        MP.ADDRESS
        --EAP.EMAIL AS PROFILE_EMAIL,
        --ASU.USER_NAME,
        --ASU.PASSWORD,
        --ASU.STATUS_CODE AS USER_STATUS
    FROM
        ENTITY E
    INNER JOIN ENTITY_ACCOUNT EA ON E.ENTITY_ID = EA.ENTITY_ID
    LEFT JOIN ENTITY_CONTACT EC ON E.ENTITY_ID = EC.ENTITY_ID
    LEFT JOIN ENTITY_ACCOUNT_PROFILE EAP ON EA.ENTITY_ACCOUNT_ID = EAP.ENTITY_ACCOUNT_ID
    LEFT JOIN MOJO_USER_PROFILE MP ON E.ENTITY_ID = MP.ENTITY_ID
    --LEFT JOIN USERS ASU ON E.ENTITY_ID = ASU.ENTITY_ID
    WHERE
        E.ENTITY_ID = P_ENTITY_ID
        AND E.ENTITY_TYPE_ID = P_ENTITY_TYPE_ID;
END GET_CONSUMER_PROFILE;

END CONSUMER_PROFILE_UTIL;







last step 3 

-- Compile the package specification
ALTER PACKAGE CONSUMER_PROFILE_UTIL COMPILE;

-- Compile the package body
ALTER PACKAGE CONSUMER_PROFILE_UTIL COMPILE BODY