CREATE OR REPLACE PROCEDURE GET_AGENT_LISTS(
    P_ENTITY_TYPE_ID IN NUMBER,
    P_RESULT_CURSOR  OUT SYS_REFCURSOR
) IS
BEGIN
    OPEN P_RESULT_CURSOR FOR
    SELECT
        E.ENTITY_ID,
        E.ENTITY_CODE,
        E.ENTITY_FIRST_NAME,
        E.ENTITY_LAST_NAME,
        E.MALE_OR_FEMALE AS GENDER,
        E.BIRTH_DATE AS DOB,
        E.REGISTRATION_DATE,
        --E.ENTITY_NATURE_ID AS COUNTRY_ID,
        EA.MSISDN AS MOBILE_NUMBER,
        EC.EMAIL,
        --EC.CONTACT_PERSON_FIRST_NAME,
        --EC.CONTACT_PERSON_EMAIL AS CONTACT_EMAIL,
        --EA.POST AS ENTITY_ACCOUNT_STATUS,
        --EAP.FIRST_NAME AS PROFILE_FIRST_NAME,
        --EAP.FAMILY_NAME AS PROFILE_LAST_NAME,
        --EAP.DATE_OF_BIRTH AS PROFILE_DOB,
        --EAP.GENDER AS PROFILE_GENDER,
        EAP.Primary_Country_Id AS PROFILE_COUNTRY_ID,
        EAP.OCCUPATION_ID,
        EAP.AVERAGE_MONTHLY_INCOME_ID,
        EAP.SOURCE_OF_FUNDS_ID
        --EAP.EMAIL AS PROFILE_EMAIL,
        --ASU.USER_NAME,
        --ASU.PASSWORD,
        --ASU.STATUS_CODE AS USER_STATUS
    FROM
        ENTITY E
    INNER JOIN ENTITY_ACCOUNT EA ON E.ENTITY_ID = EA.ENTITY_ID
    LEFT JOIN ENTITY_CONTACT EC ON E.ENTITY_ID = EC.ENTITY_ID
    LEFT JOIN ENTITY_ACCOUNT_PROFILE EAP ON EA.ENTITY_ACCOUNT_ID = EAP.ENTITY_ACCOUNT_ID
    --LEFT JOIN USERS ASU ON E.ENTITY_ID = ASU.ENTITY_ID
    WHERE
        E.ENTITY_TYPE_ID = P_ENTITY_TYPE_ID;
END GET_AGENT_LISTS;
/
