--BANK COMMISSION FOR ZENITH BANK
DECLARE
V_ENTITY_ID ENTITY.ENTITY_ID%TYPE := NULL;
V_FEE_TYPE_ROW FEE_TYPE%ROWTYPE := NULL;
V_FEE_TYPE_ID  FEE_TYPE.FEE_TYPE_ID%TYPE := 201;
BEGIN
--SELECT E.ENTITY_ID INTO V_ENTITY_ID FROM ENTITY E WHERE E.ENTITY_CODE = 'CSP';
SELECT * INTO V_FEE_TYPE_ROW FROM FEE_TYPE FT WHERE FT.ENTITY_ID = 40323 AND FT.FEE_TYPE_CODE = 'BANKCOMMISSION';
 
/*  SELECT MAX(F.FEE_TYPE_ID)+1 INTO V_FEE_TYPE_ID FROM FEE_TYPE F;
  INSERT INTO FEE_TYPE (FEE_TYPE_ID, FEE_TYPE_CODE, FEE_TYPE_NAME, FEE_TYPE_SHORT_NAME, FEE_CATEGORY_ID, ENTITY_ID, BANK_ACCOUNT_ID, POST, LOG_ID, ARREAR_FEE, PRIMARY_FEE, PENALTY_FEE, AUTO_PAYMENT_SORT_ORDER, FEE_NATURE_ID, DEFAULT_FEE, IS_QTY_ENABLED)
  VALUES (V_FEE_TYPE_ID , V_FEE_TYPE_ROW.FEE_TYPE_CODE, V_FEE_TYPE_ROW.FEE_TYPE_NAME, V_FEE_TYPE_ROW.FEE_TYPE_SHORT_NAME, V_FEE_TYPE_ROW.FEE_CATEGORY_ID, V_ENTITY_ID, V_FEE_TYPE_ROW.BANK_ACCOUNT_ID, 1, 0, 0, 0, 0, 1, NULL, 1, 0);
  */  
   INSERT INTO FEE_TYPE_BANK_ACCOUNT (RULE_ID, FEE_TYPE_ID, REGION_ID, CURRENCY_ID, BANK_ACCOUNT_ID, POST, LOG_ID)
   SELECT ROWNUM + (SELECT MAX(FTB.RULE_ID) FROM FEE_TYPE_BANK_ACCOUNT FTB),
             V_FEE_TYPE_ID,
             R.REGION_ID,
             1 CURRENCY_ID,
             V_FEE_TYPE_ROW.BANK_ACCOUNT_ID,
             1 LOG_ID,
             0 POST
      FROM REGIONS R;
END;
 
SELECT * FROM ENTITY E WHERE E.ENTITY_ID=149803;
SELECT * FROM FEE_TYPE FT WHERE FT.FEE_TYPE_ID=2703;
SELECT * FROM FEE_TYPE_BANK_ACCOUNT FT WHERE FT.FEE_TYPE_ID=2703;
--
DECLARE
V_ENTITY_ID ENTITY.ENTITY_ID%TYPE := NULL;
V_FEE_TYPE_ROW FEE_TYPE%ROWTYPE := NULL;
V_FEE_TYPE_ID  FEE_TYPE.FEE_TYPE_ID%TYPE := 2703;
BEGIN
--SELECT E.ENTITY_ID INTO V_ENTITY_ID FROM ENTITY E WHERE E.ENTITY_CODE = 'CSP';
SELECT * INTO V_FEE_TYPE_ROW FROM FEE_TYPE FT WHERE FT.ENTITY_ID = 149803 AND FT.FEE_TYPE_CODE = 'GENERALPAYMENT';
 
/*  SELECT MAX(F.FEE_TYPE_ID)+1 INTO V_FEE_TYPE_ID FROM FEE_TYPE F;
  INSERT INTO FEE_TYPE (FEE_TYPE_ID, FEE_TYPE_CODE, FEE_TYPE_NAME, FEE_TYPE_SHORT_NAME, FEE_CATEGORY_ID, ENTITY_ID, BANK_ACCOUNT_ID, POST, LOG_ID, ARREAR_FEE, PRIMARY_FEE, PENALTY_FEE, AUTO_PAYMENT_SORT_ORDER, FEE_NATURE_ID, DEFAULT_FEE, IS_QTY_ENABLED)
  VALUES (V_FEE_TYPE_ID , V_FEE_TYPE_ROW.FEE_TYPE_CODE, V_FEE_TYPE_ROW.FEE_TYPE_NAME, V_FEE_TYPE_ROW.FEE_TYPE_SHORT_NAME, V_FEE_TYPE_ROW.FEE_CATEGORY_ID, V_ENTITY_ID, V_FEE_TYPE_ROW.BANK_ACCOUNT_ID, 1, 0, 0, 0, 0, 1, NULL, 1, 0);
  */  
   INSERT INTO FEE_TYPE_BANK_ACCOUNT (RULE_ID, FEE_TYPE_ID, REGION_ID, CURRENCY_ID, BANK_ACCOUNT_ID, POST, LOG_ID)
   SELECT ROWNUM + (SELECT MAX(FTB.RULE_ID) FROM FEE_TYPE_BANK_ACCOUNT FTB),
             V_FEE_TYPE_ID,
             R.REGION_ID,
             1 CURRENCY_ID,
             V_FEE_TYPE_ROW.BANK_ACCOUNT_ID,
             1 LOG_ID,
             0 POST
      FROM REGIONS R;
END;
 
SELECT * FROM ENTITY E WHERE E.ENTITY_ID=149917;
SELECT * FROM FEE_TYPE FT WHERE FT.ENTITY_ID=149917;
SELECT * FROM FEE_TYPE_BANK_ACCOUNT FT WHERE FT.FEE_TYPE_ID=2809;
 
 
select * from bank where bank_id=14;
select * from entity where entity_id=88779;
SELECT B.BANK_ID, B.CONNECTED_ENTITY_ID
  FROM BANK_ACCOUNT BA, BANK_BRANCH BR, BANK B
  WHERE BA.BANK_BRANCH_ID = BR.BANK_BRANCH_ID
    AND BR.BANK_ID = B.BANK_ID
    AND BA.BANK_ACCOUNT_ID = 1808036;

/* GET_POOL_BANK_ACCOUNT(P_BANK_ENTITY_ID     => V_BANK_ENTITY_ID,
                                                         P_MERCHANT_ENTITY_ID => P_MERCHANT_ENTITY_ID,
                                                         P_POOL_ACCT_NATURE   => 'I',
                                                         P_CURRENCY_ID        => P_CURRENCY_ID
                                                         );*/   
insert into POOL_BANK_ACCOUNT_CONFIG (RULE_ID, BANK_ENTITY_ID, MERCHANT_ENTITY_ID, BANK_ACCOUNT_ID, POOL_ACCT_NATURE, POST, LOG_ID, CURRENCY_ID)
values (17, 88779, null, 34, 'I', 1, 0, 1);
 
insert into POOL_BANK_ACCOUNT_CONFIG (RULE_ID, BANK_ENTITY_ID, MERCHANT_ENTITY_ID, BANK_ACCOUNT_ID, POOL_ACCT_NATURE, POST, LOG_ID, CURRENCY_ID)
values (18, 88779, null, 33, 'T', 1, 0, 1);
