select * from entity_system_config order by 1 desc;




insert into entity_system_config (CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_STATUS)
values (1268, 'MTN_OPEN_API_CLIENT_URL', 'https://devsrv.cspay.app/mtnapi', 'MTN OPEN API CLIENT BASE URL');

insert into entity_system_config (CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_STATUS)
values (1269, 'MTN_OPEN_API_CLIENT_USERNAME', 'test', 'MTN OPEN API BASIC AUTH CREDS');

insert into entity_system_config (CONFIG_ID, CONFIG_KEY, CONFIG_VALUE, CONFIG_STATUS)
values (1270, 'MTN_OPEN_API_CLIENT_PASSWORD', '12345', 'MTN OPEN API BASIC AUTH CREDS');



create table MTN_POSTED_TRANSACTIONS
(
  transaction_id              NUMBER generated by default as identity,
  transaction_date            DATE,
  csg_system_id               NUMBER,
  referenceid                 VARCHAR2(50),
  transaction_type            VARCHAR2(50),
  amount                      NUMBER,
  currency                    VARCHAR2(10),
  partyidtype                 VARCHAR2(10),
  partyid                     VARCHAR2(50),
  payeenote                   VARCHAR2(500),
  payermessage                VARCHAR2(500),
  resp_financialtransactionid NUMBER,
  resp_statuscode             VARCHAR2(20),
  resp_status                 VARCHAR2(100),
  csg_status_code             VARCHAR2(10),
  csg_status_message          VARCHAR2(255),
  posted_to_mtn               VARCHAR2(1)
);


